version: '3.8'

services:
  app:
    image: arkunis/cv_theq
    ports:
      - "8081:80"
    volumes:
      - ./my-php-app:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: cv_theq
    volumes:
      - db_data:/var/lib/mysql
      - ./SQL.sql:/docker-entrypoint-initdb.d/SQL.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ""

volumes:
  db_data:
