CREATE TABLE tableName 
(
    Id	BIGINT  NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Nom	VARCHAR(512),
    Prenom	VARCHAR(512),
    Age	VARCHAR(512),
    Date_naissance	VARCHAR(512),
    Adresse	VARCHAR(512),
    Adresse_1	VARCHAR(512),
    Code_postal	VARCHAR(512),
    ville	VARCHAR(512),
    tel_portable	INT,
    tel_fixe	VARCHAR(512),
    Email	VARCHAR(512),
    Profil	VARCHAR(512),
    Competence_1	VARCHAR(512),
    Competence_2	VARCHAR(512),
    Competence_3	VARCHAR(512),
    Competence_4	VARCHAR(512),
    Competence_5	VARCHAR(512),
    Competence_6	VARCHAR(512),
    Competence_7	VARCHAR(512),
    Competence_8	VARCHAR(512),
    Competence_9	VARCHAR(512),
    Competence_10	VARCHAR(512),
    Site_Web	VARCHAR(512),
    Profil_Linkedin	VARCHAR(512),
    Profil_Viadeo	VARCHAR(512),
    Profil_facebook	VARCHAR(512)
);

INSERT INTO tableName (Id, Nom, Prenom, Age, Date_naissance, Adresse, Adresse_1, Code_postal, ville, tel_portable, tel_fixe, Email, Profil, Competence_1, Competence_2, Competence_3, Competence_4, Competence_5, Competence_6, Competence_7, Competence_8, Competence_9, Competence_10, Site_Web, Profil_Linkedin, Profil_Viadeo, Profil_facebook) VALUES ('1', 'TAMARIN', 'Margaux', NULL, '10/10/1965', NULL, NULL, NULL, NULL, '+33674000000', NULL, 'marg.tamarin@gmail.com', 'Import/Export', 'Marketing de contenu', 'Stratégie de social media', 'Webmarketing', 'Storytelling', 'Analytics', 'Rédaction', 'Anglais', NULL, NULL, NULL, 'www.margauxtamarin.com', NULL, NULL, NULL);
INSERT INTO tableName (Id, Nom, Prenom, Age, Date_naissance, Adresse, Adresse_1, Code_postal, ville, tel_portable, tel_fixe, Email, Profil, Competence_1, Competence_2, Competence_3, Competence_4, Competence_5, Competence_6, Competence_7, Competence_8, Competence_9, Competence_10, Site_Web, Profil_Linkedin, Profil_Viadeo, Profil_facebook) VALUES ('2', 'MARVELLA', 'Claudia', NULL, '06/10/1990', NULL, NULL, NULL, 'GRENOBLE', '+33674113635', NULL, 'claudia.marvella@hotmail.com', 'Digital Manager', 'Adaptation', 'Créativité', 'Leadership', 'Communication', 'Dynamisme', 'Médias sociaux', 'Prestashop', 'E-commerce', 'Salesforce', 'Commerce International', NULL, NULL, NULL, NULL);
INSERT INTO tableName (Id, Nom, Prenom, Age, Date_naissance, Adresse, Adresse_1, Code_postal, ville, tel_portable, tel_fixe, Email, Profil, Competence_1, Competence_2, Competence_3, Competence_4, Competence_5, Competence_6, Competence_7, Competence_8, Competence_9, Competence_10, Site_Web, Profil_Linkedin, Profil_Viadeo, Profil_facebook) VALUES ('3', 'ANIS', 'Nouri', NULL, '08/07/1993', 'Argoub Ezaatar Medjez', NULL, '9070', 'El Beb', '+21655934452', NULL, 'nourianis1991@gmail.com', 'Technicien réseaux', 'Windows', 'Linux', 'Réseaux', 'Français', 'Anglais', 'Arabe', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO tableName (Id, Nom, Prenom, Age, Date_naissance, Adresse, Adresse_1, Code_postal, ville, tel_portable, tel_fixe, Email, Profil, Competence_1, Competence_2, Competence_3, Competence_4, Competence_5, Competence_6, Competence_7, Competence_8, Competence_9, Competence_10, Site_Web, Profil_Linkedin, Profil_Viadeo, Profil_facebook) VALUES ('4', 'MARTIN', 'Michel', NULL, '04/09/1978', '320 avenue de la Liberté', 'apt 7B', '75000', 'Paris', '0600000000', '0100000000', 'michel.martin@primocv.com', 'Cadre commercial', 'Commerce', 'Bureautique', 'Anglais', 'Espagnol', NULL, NULL, NULL, NULL, NULL, NULL, 'www.monsite.com', NULL, NULL, NULL);
INSERT INTO tableName (Id, Nom, Prenom, Age, Date_naissance, Adresse, Adresse_1, Code_postal, ville, tel_portable, tel_fixe, Email, Profil, Competence_1, Competence_2, Competence_3, Competence_4, Competence_5, Competence_6, Competence_7, Competence_8, Competence_9, Competence_10, Site_Web, Profil_Linkedin, Profil_Viadeo, Profil_facebook) VALUES ('5', 'GIRAUD', 'Pierre', NULL, '25/01/1990', 'Impasse des Acacias', NULL, '83200', 'Toulon', '+33633298588', NULL, 'pierre.giraud@edhec.com', 'Management', 'Bureautique', 'Anglais', 'Management', 'Infographie', 'Développement Web', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO tableName (Id, Nom, Prenom, Age, Date_naissance, Adresse, Adresse_1, Code_postal, ville, tel_portable, tel_fixe, Email, Profil, Competence_1, Competence_2, Competence_3, Competence_4, Competence_5, Competence_6, Competence_7, Competence_8, Competence_9, Competence_10, Site_Web, Profil_Linkedin, Profil_Viadeo, Profil_facebook) VALUES ('6', 'MOREAU', 'Mélanie', NULL, '24/02/1975', NULL, NULL, NULL, 'PARIS', '+33674113635', NULL, 'melaniemoreau@gmail.com', 'Responsable du Service Client', 'Bureautique', 'Anglais', 'Français', 'Espagnol', 'CRM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO tableName (Id, Nom, Prenom, Age, Date_naissance, Adresse, Adresse_1, Code_postal, ville, tel_portable, tel_fixe, Email, Profil, Competence_1, Competence_2, Competence_3, Competence_4, Competence_5, Competence_6, Competence_7, Competence_8, Competence_9, Competence_10, Site_Web, Profil_Linkedin, Profil_Viadeo, Profil_facebook) VALUES ('7', 'BOUTEILLER', 'Fanny', NULL, '03/09/1986', NULL, NULL, NULL, NULL, '0688179934', NULL, 'fanny.bouteiller@gmail.com', 'Réalisatrice Rédactrice', 'Maîtrise Caméras', 'Montage', 'Anglais', 'Français', 'Belge', NULL, NULL, NULL, NULL, NULL, 'https://fannybouteiller.wordpress.com', NULL, NULL, NULL);
INSERT INTO tableName (Id, Nom, Prenom, Age, Date_naissance, Adresse, Adresse_1, Code_postal, ville, tel_portable, tel_fixe, Email, Profil, Competence_1, Competence_2, Competence_3, Competence_4, Competence_5, Competence_6, Competence_7, Competence_8, Competence_9, Competence_10, Site_Web, Profil_Linkedin, Profil_Viadeo, Profil_facebook) VALUES ('8', 'CHERET', 'Laurent', '35', '26/07/1976', '8 impasse du Languedoc', NULL, 'F-57525', 'TALANGE', '0664964404', '0387804868', 'laurent.cheret@yahoo.fr', 'Journaliste', 'Anglais', 'Allemand', 'Service client', 'Communication', 'BToB', 'BToC', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO tableName (Id, Nom, Prenom, Age, Date_naissance, Adresse, Adresse_1, Code_postal, ville, tel_portable, tel_fixe, Email, Profil, Competence_1, Competence_2, Competence_3, Competence_4, Competence_5, Competence_6, Competence_7, Competence_8, Competence_9, Competence_10, Site_Web, Profil_Linkedin, Profil_Viadeo, Profil_facebook) VALUES ('10', 'QUEVAL PAROLA', 'Sophie', '26', '01/04/1990', '22 rue fodéré', NULL, '06300', 'NICE', '06.29.05.72.66', NULL, 'sophie.queval@gmail.com', 'Communication - Marketing', 'Communication Interne', 'Communication Externe', 'Communication Institutionelle', 'Relations Presse', NULL, NULL, NULL, NULL, NULL, NULL, 'sophiequevalparola.wordpress.com', NULL, NULL, NULL);
INSERT INTO tableName (Id, Nom, Prenom, Age, Date_naissance, Adresse, Adresse_1, Code_postal, ville, tel_portable, tel_fixe, Email, Profil, Competence_1, Competence_2, Competence_3, Competence_4, Competence_5, Competence_6, Competence_7, Competence_8, Competence_9, Competence_10, Site_Web, Profil_Linkedin, Profil_Viadeo, Profil_facebook) VALUES ('11', 'LAGARDERE', 'Alfred', NULL, '03/03/1975', NULL, NULL, NULL, 'PARIS', '+33674113635', NULL, 'marinelagard@gmail.com', 'Français', 'Anglais', 'Espagnol', 'Italien', 'CRM', 'Bureautique', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO tableName (Id, Nom, Prenom, Age, Date_naissance, Adresse, Adresse_1, Code_postal, ville, tel_portable, tel_fixe, Email, Profil, Competence_1, Competence_2, Competence_3, Competence_4, Competence_5, Competence_6, Competence_7, Competence_8, Competence_9, Competence_10, Site_Web, Profil_Linkedin, Profil_Viadeo, Profil_facebook) VALUES ('12', 'LEVEQUE', 'Emile', NULL, '13/11/1990', '84 rue du Bas-Coudray', NULL, '91100', 'CORBEIL-ESSONNES', '0674928161', NULL, 'leveque.emile@live.fr', 'Communication', 'Anglais', 'PAO', 'Montage', 'Bureautique', 'Communication', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO tableName (Id, Nom, Prenom, Age, Date_naissance, Adresse, Adresse_1, Code_postal, ville, tel_portable, tel_fixe, Email, Profil, Competence_1, Competence_2, Competence_3, Competence_4, Competence_5, Competence_6, Competence_7, Competence_8, Competence_9, Competence_10, Site_Web, Profil_Linkedin, Profil_Viadeo, Profil_facebook) VALUES ('13', 'FARRÉ', 'Aladin', '24', '13/03/1992', '3 rue du lieutenant Chauré', NULL, '75020', 'PARIS', '0684944836', NULL, 'aladinfarre@gmail.com', 'Ingénieur Audiovisuel', 'Anglais', 'Montage', 'Maîtrise Caméras', 'Allemand', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO tableName (Id, Nom, Prenom, Age, Date_naissance, Adresse, Adresse_1, Code_postal, ville, tel_portable, tel_fixe, Email, Profil, Competence_1, Competence_2, Competence_3, Competence_4, Competence_5, Competence_6, Competence_7, Competence_8, Competence_9, Competence_10, Site_Web, Profil_Linkedin, Profil_Viadeo, Profil_facebook) VALUES ('14', 'GUIOT', 'Laura', '25', '14/02/1991', NULL, NULL, NULL, 'BRUXELLES', '+32486739013', NULL, 'lauraguiot@gmail.com', 'Editrice Web', 'Communication', 'Anglais', 'Français', 'Néerlandais', 'Social Médias', 'Rédaction', 'Wordpress', NULL, NULL, NULL, 'jefaisdubruit.com', NULL, NULL, NULL);
